// server/src/services/k6-generator/render-script.ts
import { K6_IMPORTS, fixedHelpers, handleSummarySource } from './template.js';
import type { SteadyWindow } from './window.js';
import type { K6Scenario } from './scenarios.js';

export type AssembleParts = {
  window: SteadyWindow;
  scenarios: Record<string, K6Scenario>;
  thresholds: Record<string, string[]>;
  execModel: 'weighted-loop' | 'per-scenario';
  execFnsSource: string;     // the exported exec function(s): router() or per-workflow fns
  hasReusable: boolean;
  hasConsumable: boolean;
};

const SUMMARY_TREND_STATS = ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)', 'count'];

export function assembleScript(p: AssembleParts): string {
  const options = {
    scenarios: p.scenarios,
    thresholds: p.thresholds,
    summaryTrendStats: SUMMARY_TREND_STATS,
  };

  const dataDecls: string[] = [];
  if (p.hasReusable) dataDecls.push('var reusable = new SharedArray("reusable", function () { return JSON.parse(open("./reusable.json")); });');
  if (p.hasConsumable) dataDecls.push('var consumable = new SharedArray("consumable", function () { return JSON.parse(open("./consumable.json")); });');

  return [
    '// GENERATED by Sentinel k6-generator (v1 HTTP/sync, scratch). Do not hand-edit; regenerate.',
    K6_IMPORTS,
    '',
    '// --- Environment (injected per-run by the harness) ---',
    'var BASE = __ENV.BASE_URL;',
    'var TEST_RUN_ID = __ENV.TEST_RUN_ID;',
    'var AUTH_TOKEN = __ENV.AUTH_TOKEN || "";',
    '',
    '// --- Baked steady-state window boundaries (overridable via env; seconds) ---',
    `var WARMUP_END_S = Number(__ENV.WARMUP_END_S || ${p.window.warmupEndS});`,
    `var RAMP_UP_END_S = Number(__ENV.RAMP_UP_END_S || ${p.window.rampUpEndS});`,
    `var STEADY_END_S = Number(__ENV.STEADY_END_S || ${p.window.steadyEndS});`,
    '',
    ...(dataDecls.length ? ['// --- Data ---', ...dataDecls, ''] : []),
    fixedHelpers(),
    '',
    `export const options = ${JSON.stringify(options, null, 2)};`,
    '',
    'export function setup() {',
    '  // Consumable volume is verified at generation time (expectedIterations); claimConsumable aborts on shortfall.',
    '  return { runId: TEST_RUN_ID };',
    '}',
    'export function teardown() {}',
    '',
    '// --- Exec functions ---',
    p.execFnsSource,
    '',
    handleSummarySource(),
    '',
  ].join('\n');
}
